"""add gst_number to vendors

Revision ID: fc42a7cf9189
Revises: 093ed85321c8
Create Date: 2026-06-24 08:10:10.593117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc42a7cf9189'
down_revision: Union[str, None] = '093ed85321c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_vendors', sa.Column('gst_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_vendors', 'gst_number')
    # ### end Alembic commands ###
