"""add gst_number logo to airlines

Revision ID: 093ed85321c8
Revises: c41d8a9c20b5
Create Date: 2026-06-24 07:54:39.854657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093ed85321c8'
down_revision: Union[str, None] = 'c41d8a9c20b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airlines', sa.Column('gst_number', sa.String(length=50), nullable=True))
    op.add_column('airlines', sa.Column('logo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airlines', 'logo')
    op.drop_column('airlines', 'gst_number')
    # ### end Alembic commands ###
