"""initial_schema

Revision ID: c41d8a9c20b5
Revises: 
Create Date: 2026-06-23 21:34:54.907625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41d8a9c20b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline_code', sa.String(length=20), nullable=False),
    sa.Column('airline_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airlines_airline_code'), 'airlines', ['airline_code'], unique=True)
    op.create_index(op.f('ix_airlines_id'), 'airlines', ['id'], unique=False)
    op.create_table('fuel_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_code', sa.String(length=20), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_vendors_id'), 'fuel_vendors', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_vendors_vendor_code'), 'fuel_vendors', ['vendor_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'viewer', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('fuel_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('price_per_liter', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['fuel_vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_prices_id'), 'fuel_prices', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_prices_vendor_id'), 'fuel_prices', ['vendor_id'], unique=False)
    op.create_table('fuel_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('fuel_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('fuel_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['fuel_vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_transactions_airline_id'), 'fuel_transactions', ['airline_id'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_id'), 'fuel_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_invoice_no'), 'fuel_transactions', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_fuel_transactions_transaction_date'), 'fuel_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_vendor_id'), 'fuel_transactions', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_transactions_vendor_id'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_transaction_date'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_invoice_no'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_id'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_airline_id'), table_name='fuel_transactions')
    op.drop_table('fuel_transactions')
    op.drop_index(op.f('ix_fuel_prices_vendor_id'), table_name='fuel_prices')
    op.drop_index(op.f('ix_fuel_prices_id'), table_name='fuel_prices')
    op.drop_table('fuel_prices')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fuel_vendors_vendor_code'), table_name='fuel_vendors')
    op.drop_index(op.f('ix_fuel_vendors_id'), table_name='fuel_vendors')
    op.drop_table('fuel_vendors')
    op.drop_index(op.f('ix_airlines_id'), table_name='airlines')
    op.drop_index(op.f('ix_airlines_airline_code'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###
